language: minimal
install:
  - DD_API_KEY=$DD_API_KEY bash -c "$(curl -L https://raw.githubusercontent.com/DataDog/datadog-agent/master/cmd/agent/install_script.sh)"
script:
  - ps -ef
  - systemctl status datadog-agent
  - hostname
